import {
  AlertTriangle,
  BarChart3,
  Book,
  BookA,
  BookMarked,
  BookOpen,
  Box,
  Brain,
  Briefcase,
  Calculator,
  CalendarClock,
  CalendarRange,
  CheckCircle,
  Cpu,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Columns3,
  Database,
  FileCode,
  FileQuestion,
  FileText,
  FlaskConical,
  Gauge,
  GitCompare,
  GitMerge,
  Globe,
  HelpCircle,
  Info,
  Layers,
  LayoutGrid,
  Library,
  Lightbulb,
  List,
  ListChecks,
  ListTodo,
  Network,
  Package,
  Palette,
  Pencil,
  Plug,
  Search,
  ScanSearch,
  Settings2,
  Shield,
  Sigma,
  Sliders,
  Sparkle,
  Sparkles,
  Star,
  Table,
  Table2,
  Tag,
  Target,
  TrendingUp,
  User,
  Users,
  Waypoints,
  Workflow,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "alert-triangle": AlertTriangle,
  "bar-chart-3": BarChart3,
  book: Book,
  "book-a": BookA,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  bookmark: BookMarked,
  box: Box,
  brain: Brain,
  briefcase: Briefcase,
  calculator: Calculator,
  "calendar-clock": CalendarClock,
  "calendar-range": CalendarRange,
  "check-circle": CheckCircle,
  cpu: Cpu,
  clipboard: Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "columns-3": Columns3,
  database: Database,
  "file-code": FileCode,
  "file-question": FileQuestion,
  "file-text": FileText,
  "flask-conical": FlaskConical,
  gauge: Gauge,
  "git-compare": GitCompare,
  "git-merge": GitMerge,
  globe: Globe,
  "help-circle": HelpCircle,
  info: Info,
  layers: Layers,
  "layout-grid": LayoutGrid,
  library: Library,
  lightbulb: Lightbulb,
  list: List,
  "list-checks": ListChecks,
  "list-todo": ListTodo,
  "message-circle-question": HelpCircle,
  network: Network,
  package: Package,
  palette: Palette,
  pencil: Pencil,
  plug: Plug,
  search: Search,
  "scan-search": ScanSearch,
  "settings-2": Settings2,
  shield: Shield,
  sigma: Sigma,
  "sliders-horizontal": Sliders,
  sparkle: Sparkle,
  sparkles: Sparkles,
  star: Star,
  table: Table,
  "table-2": Table2,
  tag: Tag,
  target: Target,
  "trending-up": TrendingUp,
  user: User,
  users: Users,
  waypoints: Waypoints,
  workflow: Workflow,
};

export function getToolIcon(icon: string): LucideIcon {
  return ICONS[icon] || Sparkles;
}
